apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: caa-block-libvirt
parameters:
  cloudProvider: libvirt
  cloudProviderVolumePath: /home/madnan/VirtualMachines
provisioner: caa-csi-block.csi.confidentialcontainers.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
