apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: caa-block-aws
parameters:
  cloudProvider: aws
  awsRegion: us-east-2
  awsAvailabilityZone: us-east-2c
  awsVolumeType: gp3
provisioner: caa-csi-block.csi.confidentialcontainers.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
